### PR TITLE
Extend `andika` builtin

### PR DESCRIPTION
**Pull request by gekkowrld**
- **fix: Handle `nil` dereference in expressions**
- **style: Use `gofmt` to format the go code**
- **chore: Successfully seperate the builtins**
- **chore: Create a basic string manipulation**
- **style: Use gofmt to format the code**

Fixes: https://github.com/NuruProgramming/Nuru/issues/81

What hasn't been done:

Check types before doing the substitution.
Error checks.

### CODE REVIEW

**Comment by gekkowrld** [comment]
Added:
Type checks
Error checks
Support for flags

**Comment by AvicennaJr** [comment]
These are my thoughts:

1. I am unsure as to what the pull request does exactly. Kindly explain with examples of how it was before and how it is with your changes.
2. I feel like these are too many changes for one pull request.

**Comment by AvicennaJr** [comment]
I did also test:

Screenshot_20240609_162149

**Comment by gekkowrld** [comment]
> These are my thoughts:
> 
>     1. I am unsure as to what the pull request does exactly. Kindly explain with examples of how it was before and how it is with your changes.

It tries to implement as explained in #81 c-style formatting. The only difference being the 'characters' used. I used characters as used in `swahili` e.g `%s` for `safu`, `%t` for `tungo` and so on.
An example:

```nuru
jina = "Jabari"
matunda = ["Ndimu", "Limau", "Chungwa"]

andika("%t ana %s kwenye kikapu chake.", jina, matunda)
// Jabari ana [Ndimu, Limau, Chungwa] kwenye kikapu chake.
```

> 
>     2. I feel like these are too many changes for one pull request.

I agree, most of the 'changes' are really the ones that were made by running `gofmt -w -s .`. I only focuses on a few files that directly related with `andika` function.

**Comment by gekkowrld** [comment]
Should have string manipulation instead

**Pull request closed without merging**
