### PR TITLE
Implement format string

### PR DESCRIPTION
**Pull request by gekkowrld**
The formatting follows the following style:
    andika("") // nothing
    andika() // newline (historical reasons)
    andika("hello") // hello
    andika("mimi ni {0} niko hapa {1} kama {0}", "Nuru", "github")
	// mimi ni Nuru niko hapa github kama Nuru
    andika("{0}") // error
    andika("", "") // error

The errors are still generic with no helpful information.
This is not an issue with this pr only but deeper so future problem.

This is potentially solves <https://github.com/NuruProgramming/Nuru/issues/81>
and successor to <https://github.com/NuruProgramming/Nuru/pull/82>

Actually does "Should have string manipulation instead" <https://github.com/NuruProgramming/Nuru/pull/82#issuecomment-2393490476>

### CODE REVIEW

**Comment by AvicennaJr** [comment]
Here are my thoughts:

1. ` andika("mimi ni {0} niko hapa {1} kama {0}", "Nuru", "github")` will break the syntax of how Nuru currently works:

Screenshot_20241030_102200

2. What if someone wanted to print `{0}`? Since `{` and `}` are not escape characters this is not possible.
3. There is no reason for `andika("", "") ` to throw an error

My advice would be to add string formatting to the string object itself, I've included examples in Go and Python:

1. Python:

Screenshot_20241030_105330

2. Go:

Screenshot_20241030_110123

**Comment by gekkowrld** [comment]
> andika("mimi ni {0} niko hapa {1} kama {0}", "Nuru", "github") will break the syntax of how Nuru currently works:

True but not many programs will be affected.

> What if someone wanted to print {0}? Since { and } are not escape characters this is not possible.

Fixed in comit <https://github.com/NuruProgramming/Nuru/pull/93/commits/f49a4b7bc20f1cc63c2a77962d3ed2972c7a225f>

> There is no reason for andika("", "") to throw an error

This is an invalid syntax, Go (the golps lsp atleast) throws  a warning and go itself prints "%!(EXTRA string=)".
This is done on the Printf, but println works just fine.

> My advice would be to add string formatting to the string object itself, I've included examples in Go and Python:

Python does have that only on `fstring`, the .format just iterates over the string object mutating as it goes by.
Look at <https://github.com/python/cpython/blob/main/Lib/string.py> for .format()
Look at <https://docs.python.org/3/reference/lexical_analysis.html#f-strings> for fstrings (they are baked into the lexical stage)
Lexing fstring starts here <https://github.com/python/cpython/blob/main/Parser/lexer/lexer.c#L1063>

Go doesn't have string `object`, because a string is just a sequence of bytes to it.
The formatting is done by Printf and Sprintf (`f` for formatting), all the others like Println, Print and so on
will just ignore the '%s' syntax as its not a special token in go itself but an added on by the stdlib

Look at the '%' formatting here <https://github.com/golang/go/blob/master/src/fmt/print.go>
and the whole module for other things like '%#'... <https://github.com/golang/go/blob/master/src/fmt>

**Comment by AvicennaJr** [comment]
```
Python does have that only on fstring, the .format just iterates over the string object mutating as it goes by.
Look at https://github.com/python/cpython/blob/main/Lib/string.py for .format()
```

So the equivalent in Nuru would be to do it on the [String object](https://github.com/NuruProgramming/Nuru/blob/main/object/strings.go), and not the built-in `andika` function right?

**Comment by AvicennaJr** [comment]
Consider a case where someone wants to format a string and assign it to a variable, how would one achieve that with your implementation?

**Comment by gekkowrld** [comment]
> So the equivalent in Nuru would be to do it on the String object, and not the built-in andika function right?

Yes, so something like `"Jina ni {0}\n".unda("Nuru")`. 

This will mean that the andika() function can be used as before.

**Comment by gekkowrld** [comment]
> Consider a case where someone wants to format a string and assign it to a variable, how would one achieve that with your implementation?

We could have added another function for formatting e.g unda() and then by default call it for formatting and print the resulting string, like your example in golang `Sprintf`

**Comment by AvicennaJr** [comment]
> Yes, so something like "Jina ni {0}\n".unda("Nuru").

Yep, but probably a different name (don't wanna confuse people with unda).

> This will mean that the andika() function can be used as before.

Exactly

> We could have added another function for formatting e.g unda() and then by default call it for formatting and print the resulting string, like your example in golang Sprintf

This will add unnecessary complexity. Let's go with modifying the String object. If you agree, kindly close this PR and make a new one.

**Comment by gekkowrld** [comment]
> Yep, but probably a different name (don't wanna confuse people with unda).

What other name conveys that it will be formatting without confusion?

**Comment by AvicennaJr** [comment]
> What other name conveys that it will be formatting without confusion?

Not sure :sweat_smile:

**Comment by gekkowrld** [comment]
I'll just use unda until a better name is found.
Will close this one once i open another pr

**Comment by gekkowrld** [comment]
Look at: https://github.com/NuruProgramming/Nuru/pull/94

**Pull request closed without merging**
